CREATE DATABASE db_blog;

use db_blog;

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `user_t`
CREATE TABLE `user_t` (
  `id` int NOT NULL COMMIT '主键id',
  `username` varchar(255) NOT NULL COMMIT '用户名称',
  `password` varchar(64) NOT NULL COMMIT '用户密码MD5',
  `create_date` int(12) NOT NULL COMMIT '创建时间',
  `update_date` int(12) NOT NULL COMMIT '更新时间',
  `del_flag` bit NOT NULL COMMIT '删除标志位',
  `head_image` text NOT NULL COMMIT '用户头像',
  PRIMARY KEY (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog, v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `about_t`
CREATE TABLE `about_t` (
  `id` int NOT NULL COMMIT '主键ID',
  `user_id` int NOT NULL COMMIT '用户ID',
  `content` text NOT NULL COMMIT '内容',
  `del_flag` bit NOT NULL COMMIT '删除标志位置',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_1` (`user_id`) COMMIT '用户外键',
  CONSTRAINT `FK_13` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `user_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `classificat_t`
CREATE TABLE `classificat_t` (
  `id` int NOT NULL COMMIT '',
  `name` varchar(255) NOT NULL COMMIT '',
  `pid` int NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  `sort` int NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_2` (`user_id`) COMMIT '',
  CONSTRAINT `FK_8` FOREIGN KEY `FK_2` (`user_id`) REFERENCES `user_t` (`id`) COMMIT '',
  KEY `FK_3` (`pid`) COMMIT '',
  CONSTRAINT `FK_9` FOREIGN KEY `FK_3` (`pid`) REFERENCES `classificat_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `tag_t`
CREATE TABLE `tag_t` (
  `id` int NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  `label` varchar(255) NOT NULL COMMIT '',
  `value` varchar(255) NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_1` (`user_id`) COMMIT '',
  CONSTRAINT `FK_3` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `user_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `doc_t`
CREATE TABLE `doc_t` (
  `id` int(11) NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  `classificat_id` int NOT NULL COMMIT '',
  `contaner` longtext NOT NULL COMMIT '',
  `create_date` int(12) NOT NULL COMMIT '',
  `update_date` int(12) NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  `title` text NOT NULL COMMIT '',
  `abstract` text NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_1` (`user_id`) COMMIT '',
  CONSTRAINT `FK_1` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `user_t` (`id`) COMMIT '',
  KEY `FK_3` (`classificat_id`) COMMIT '',
  CONSTRAINT `FK_7` FOREIGN KEY `FK_3` (`classificat_id`) REFERENCES `classificat_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `daemon_t`
CREATE TABLE `daemon_t` (
  `id` int NOT NULL COMMIT '',
  `host` varchar(255) NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  `create_date` int(12) NOT NULL COMMIT '',
  `update_date` int(12) NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_2` (`user_id`) COMMIT '',
  CONSTRAINT `FK_10` FOREIGN KEY `FK_2` (`user_id`) REFERENCES `user_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `doc_history_t`
CREATE TABLE `doc_history_t` (
  `id` int NOT NULL COMMIT '',
  `doc_id` int(11) NOT NULL COMMIT '',
  `contaner` longtext NOT NULL COMMIT '',
  `create_date` int(12) NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  `title` text NOT NULL COMMIT '',
  `abstract` text NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_1` (`doc_id`) COMMIT '',
  CONSTRAINT `FK_6` FOREIGN KEY `FK_1` (`doc_id`) REFERENCES `doc_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `doc_tags`
CREATE TABLE `doc_tags` (
  `id` int NOT NULL COMMIT '',
  `doc_id` int(11) NOT NULL COMMIT '',
  `tag_id` int NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_1` (`doc_id`) COMMIT '',
  CONSTRAINT `FK_4` FOREIGN KEY `FK_1` (`doc_id`) REFERENCES `doc_t` (`id`) COMMIT '',
  KEY `FK_3` (`tag_id`) COMMIT '',
  CONSTRAINT `FK_5` FOREIGN KEY `FK_3` (`tag_id`) REFERENCES `tag_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `image_t`
CREATE TABLE `image_t` (
  `id` int NOT NULL COMMIT '',
  `hash` varchar(255) NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  `url` text NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_2` (`user_id`) COMMIT '',
  CONSTRAINT `FK_2` FOREIGN KEY `FK_2` (`user_id`) REFERENCES `user_t` (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: blog  COMMIT '', v6 by langhamdario8vnh1310@gmail.com **
-- ************************************** `user_read_history_t`
CREATE TABLE `user_read_history_t` (
  `id` int NOT NULL COMMIT '',
  `user_id` int NOT NULL COMMIT '',
  `doc_t` int(11) NOT NULL COMMIT '',
  `crete_date` int(12) NOT NULL COMMIT '',
  `del_flag` bit NOT NULL COMMIT '',
  PRIMARY KEY (`id`) COMMIT '',
  KEY `FK_1` (`user_id`) COMMIT '',
  CONSTRAINT `FK_11` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `user_t` (`id`) COMMIT '',
  KEY `FK_3` (`doc_t`) COMMIT '',
  CONSTRAINT `FK_12` FOREIGN KEY `FK_3` (`doc_t`) REFERENCES `doc_t` (`id`)
);